# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set environment variables for non-interactive apt installation
ENV PYTHONUNBUFFERED 1
ENV DEBIAN_FRONTEND=noninteractive

# Set the working directory in the container
WORKDIR /djangopro

# Copy the requirements file into the container
COPY requirements.txt /djangopro/

# Install any needed packages specified in requirements.txt
RUN pip install -r requirements.txt

# Copy the current directory contents into the container at /app
COPY . /djangopro/

# CMD python manage.py runserver 0.0.0.0:8000
# Expose the port your application will run on (default is 8000)
EXPOSE 8000
