  PROCEDURE TRANSFERT_ENQEXT_AUTO (IDTRAV IN VARCHAR2,CODTYPE IN VARCHAR2, USERNAME IN VARCHAR2)
  AS 
    --CURSOR C1 IS SELECT * FROM PERSONNE_TEMP_ENQEXT ORDER BY NORDRE ASC FETCH FIRST 10 ROWS only;
    CURSOR C1 IS SELECT * FROM DBASE.PERSONNE_TEMP_ENQEXT ORDER BY NORDRE ASC;
    RW DBASE.PERSONNE_TEMP_ENQEXT%ROWTYPE;
    CURSOR C_PERS(CINAT VARCHAR2) IS  SELECT COUNT(*) FROM DBASE.PERSONNE WHERE CIN=CINAT;
  
    CNT PLS_INTEGER;
    IDTYPE VARCHAR2(6);
    DATE_DEM DATE;
    TADHMIN VARCHAR2(10);
    CODE_DEM VARCHAR2(12);
    TYP_ENQ1 VARCHAR2(200); 
    ID_DEM NUMBER(10);
    resul int;
  
  BEGIN
    UPDATE DBASE.PERSONNE_TEMP_ENQEXT  
    SET CIN=LPAD(CIN,8,'0');
    COMMIT;
    SELECT DATE_COUR INTO DATE_DEM FROM DBASE.SE_TRAVAIL WHERE ID_TRAVAIL=IDTRAV;
    dbms_output.put_line( 'DATE_DEM='||DATE_DEM ) ;
    OPEN C1;
    LOOP
      FETCH C1 INTO RW ;
      EXIT WHEN C1%NOTFOUND;
      dbms_output.put_line( 'CIN='||RW.CIN ) ;
      OPEN C_PERS(RW.CIN);
      FETCH C_PERS INTO CNT;
        dbms_output.put_line( 'CNT='||CNT ) ;
        SELECT TYPENQ1,ID_TYPE INTO TYP_ENQ1,IDTYPE FROM DBASE.CODE_RES_ENQ_EXT WHERE CODTYP1=CODTYPE;
        TADHMIN:=GET_TADHMIN_EXT(DATE_DEM,IDTYPE);
        dbms_output.put_line( 'TADHMIN='||TADHMIN ) ;
        CODE_DEM:=TO_CHAR(DATE_DEM,'YY')||'/'||IDTYPE||'/'||TADHMIN;
        dbms_output.put_line( 'CODE_DEM='||CODE_DEM ) ;
      IF CNT=0 THEN
        INSERT INTO DBASE.PERSONNE(CIN,PRENOM,PRENPERE,PRENGPERE,NOM,SEX,NOMPRENMERE,DATNAIS,LIEUNAIS,DATECIN,SITFAM,RESIDENCE,NATIONALITE,PROFESSION,NATORIGIN) 
        VALUES (RW.CIN,RW.PRENOM,RW.PRENPERE,RW.PRENGPERE,RW.NOM,RW.SEX,RW.NOMPRENMERE,TO_DATE(RW.DATNAIS,'DD/MM/YYYY'),RW.LIEUNAIS,TO_DATE(RW.DATECIN,'DD/MM/YYYY'),RW.SITFAM,RW.RESIDENCE,RW.NATIONALITE,RW.PROFESSION,'ADF_INS');
        COMMIT;
        insert INTO DBASE.ENQUETE_EXT(PERSONNE_CIN,ID_TRAVAIL,DATEREF,TYPE_ENQ_EXT_ID_TYPE,ENQ_EXT_CODTYP1,TYPENQ1,TADHMIN,CODE_DEM,USER_UPDATE,DATE_UPDATE) 
        VALUES(RW.CIN,IDTRAV,DATE_DEM,IDTYPE,CODTYPE,TYP_ENQ1,TADHMIN,CODE_DEM,USERNAME,CURRENT_TIMESTAMP);
        COMMIT;
        DELETE FROM DBASE.PERSONNE_TEMP_ENQEXT WHERE CIN = RW.CIN;
        COMMIT;
    
-- NEW PROC

      ELSE
      IF (RW.RESIDENCE is null) THEN
        UPDATE DBASE.PERSONNE SET 
      --DATECIN=TO_DATE(RW.DATECIN,'DD-MM-YYYY')
        SITFAM=RW.SITFAM
     -- ,RESIDENCE=RW.RESIDENCE
        ,PROFESSION=RW.PROFESSION
        ,NATORIGIN='ADF_UPD'
        where CIN=RW.CIN;
      Else 
        UPDATE DBASE.PERSONNE SET 
      --DATECIN=TO_DATE(RW.DATECIN,'DD-MM-YYYY')
        SITFAM=RW.SITFAM
        ,RESIDENCE=RW.RESIDENCE
        ,PROFESSION=RW.PROFESSION
        ,NATORIGIN='ADF_UPD'
        where CIN=RW.CIN;
      end if ;
      --update personne set DATECIN=TO_DATE(RW.DATECIN,'DD-MM-YYYY') where CIN=RW.CIN;
        COMMIT;
        if (codtype in ('11','12','13','15','16','17','23','24','25','26','14','46أ','42د','443','401','46','40','27','28','270','440')) then --codtype
              insert INTO DBASE.ENQUETE_EXT(PERSONNE_CIN,ID_TRAVAIL,DATEREF,TYPE_ENQ_EXT_ID_TYPE,ENQ_EXT_CODTYP1,TYPENQ1,TADHMIN,CODE_DEM,USER_UPDATE,DATE_UPDATE) 
              VALUES(RW.CIN,IDTRAV,DATE_DEM,IDTYPE,CODTYPE,TYP_ENQ1,TADHMIN,CODE_DEM,USERNAME,CURRENT_TIMESTAMP);
              commit ; 
              else  -- codtype different des valeurs precedent
            
        select count(*) into resul from DBASE.ENQUETE_EXT where PERSONNE_CIN=RW.CIN and ID_TRAVAIL in (select ID_TRAVAIL from DBASE.SE_TRAVAIl where to_char(to_date(SE_TRAVAIL.DATE_CREATION,'dd/MM/yyyy'),'yyyy') = to_char(to_date(SYSDATE,'dd/MM/yyyy'),'yyyy'));
      --select count(*) into resul from enquete_ext where PERSONNE_CIN=RW.CIN and ID_TRAVAIL in (select ID_TRAVAIL from SE_TRAVAIl where SE_TRAVAIL.DATE_CREATION > '01-01-2020');
        if (resul = 0) then
              insert INTO DBASE.ENQUETE_EXT(PERSONNE_CIN,ID_TRAVAIL,DATEREF,TYPE_ENQ_EXT_ID_TYPE,ENQ_EXT_CODTYP1,TYPENQ1,TADHMIN,CODE_DEM,USER_UPDATE,DATE_UPDATE) 
              VALUES(RW.CIN,IDTRAV,DATE_DEM,IDTYPE,CODTYPE,TYP_ENQ1,TADHMIN,CODE_DEM,USERNAME,CURRENT_TIMESTAMP);
        end if;
        COMMIT;
        end if ; -- fin codtype
      END IF;
      CLOSE C_PERS;
      CNT:=0;  
    END LOOP;
    CLOSE C1;
  
  END TRANSFERT_ENQEXT_AUTO;